### ISSUE TITLE
Destructor visibility and minor points

### ISSUE THREAD

**Issue by aimable-citron** [vovkos/doxyrest#23]
Hello,

I love doxyrest, very nice tool!
I have a weird behavior with destructors. I would like to see all the functions like under doxygen so I wrote "EXCLUDE_DESTRUCTORS = false" in doxyrest-config.lua but my destructors still don't appear. I use the version 2.0.0.

Another point concerns the include file from the class. It appear upon the classe but in the same block. I find it not clear because we would believe it is written in the class and don't necessarily understand that it's the file we must include.

My last point concerns the css. If I use the rtd theme, my text appears big, can we get the default size of the text and avoid any css added?

regards

**Comment by vovkos** [comment]
Apologies for a late reply and thank you for your feedback,  I'm really glad you find Doxyrest useful in your line of work!

1. I pushed a fix for the destructors-never-shown issue. The fix is frame-only, so you don't even have to rebuild Doxyrest -- just fetch the latest frames from github.

2. As a matter of fact, originally the include info was separated from the overview, but was later merged into a single overview code-block -- after a suggestion from our designer. So I would keep the way it is right now as the default. But -- we can introduce a setting for (optionally) placing the include info into a separate code-block.  Please create a featre request for this new setting (so we can keep this current issue for the destructors-never-shown bug).

3. CSS -- custom styling is achieved by overwriting the stock ``.css`` files with your own ones, as suggested in ``README/4. Play With Styles``. This is how it's designed to work in Sphinx. Of course, you can also modify the default ``.css`` files in your installation folder ``doxyrest/sphinx/css/doxyrest-sphinx_rtd_theme.css`` -- but that's not a recommended approach.

**Comment by aimable-citron** [comment]
Ok, thank you for the answer and the fix!

regards
