### ISSUE TITLE
c_index.rst.in missing in the tree that doxyrest_b refers to

### ISSUE THREAD

**Issue by mestaritonttu** [vovkos/doxyrest#3]
Yep, for some reason it is referring to an outdated tree.

**Comment by vovkos** [comment]
`doxyrest_b` is outdated at the moment, yes. For a quick fix, run (inside `doxyrest_b` repo):

```
git submodule foreach git checkout master
git submodule foreach git pull

```  
For a real fix, Travis CI scripts of `doxyrest` repo need to be changed so that on each successful build of `doxyrest`, `doxyrest_b` repo switches both of its submodules to the heads of upstream branches. This way, `doxyrest_b` will always be up to date.

**Comment by vovkos** [comment]
The last commit added build notifications on both Travis CI and AppVeyor CI. A web hook on jancy.org listens for these notifications. Whenever a commit to 'master' branch is successfully built/tested on both Travis CI and AppVeyor CI a new commit to the bundle repo 'doxyrest_b' is created and pushed. 

This way we can ensure a great degree of coherence between the main project repo (doxyrest) and the build-helper bundle repo (doxyrest_b).
