### ISSUE TITLE
Cryptic error

### ISSUE THREAD

**Issue by MrKepzie** [vovkos/doxyrest#34]
Hi,
doxyrest is failing for a cryptic reason:

error: [string "/Users/alexandre/development/comper/Documenta..."]:14: [string "/Users/alexandre/development/comper/Documenta..."]:44: [string "/Users/alexandre/development/comper/Documenta..."]:30: [string "/Users/alexandre/development/comper/Documenta..."]:87: [string "/Users/alexandre/development/comper/Documenta..."]:23: attempt to call a nil value (global 'getItemImportString')

Any help appreciated

Also, Is there a way to get a proper traceback ?

**Comment by vovkos** [comment]
Hi, 

Thanks for the report.

Yeah, Lua backtrace path truncation is an old-time issue -- Lua truncates paths to some ridiculously short length limit; to fix that you are expected to *rebuild* Lua yourself with a redefined limit constant (which nobody does, of course). When making Doxyrest GitHub releases, I probably should build Lua with an increased file path limit instead of getting ready-to-use Lua packages (I link them to Doxyrest statically anyway).

As of now, the easiest way to get readable Lua backtraces is to place Doxyrest frames for Lua into a shorter path (e.g. /Users/alexandere/doxyrest-frame/).

Also, if you upload your project here, I will take a look and see where this error is coming from.

**Comment by MrKepzie** [comment]
Hi,
Thank yo ufor your answer. Here attached doxyrest-config.lua and 
[doxyrest-config.txt](https://github.com/vovkos/doxyrest/files/5276348/doxyrest-config.txt)

I compiled doxyrest locally as well as lua with LUA_IDSIZE=512 in luaconf.h to get large paths.
I copied the entire **frame** directory next to doxyrest-config.lua. 

I invoke doxyrest like this:

`../doxyrest_b/build/doxyrest/bin/Release/doxyrest -c doxyrest-config.lua -f frame/common/index_main.rst.in`

Am i supposed to modify index_main.rst.in somehow ?

I get the following error:

error: [string "/Users/alexandre/development/comper/Documentation/internal_dev/doxyrest-frame/common/index_main.rst.in"]:26: attempt to call a nil value (global 'getTitle')

**Comment by MrKepzie** [comment]
Okay so I just figured out that it was my bad:
1)  I didn't update the doxyrest-config.lua search paths for the frame file
2) I wasn't using the frame/cfamily/index.rst.in  

Works great now! Much faster than Exhale and actually doesn't crash unlike Exhale.

Just need to play with the template rst files now so that I can split the index across files. Right now I spits out a 3.5Mb genindex.html
