### ISSUE TITLE
"Cannot allocate memory" on Linux

### ISSUE THREAD

**Issue by johanseland** [vovkos/doxyrest#38]
I am trying to run Doxyrest on a large Doxygen output and it crashes after approx 30s with the following error:
The directory I am trying to process contains approximately 7000 Doxygen generated XML files.
The same Doxygen output is processed just fine on Windows, albeit it takes some minutes to complete.

The Doxyrest process exists with the following error message:

`error: [string "/home/johan/data/src/huespace/extern/redhat-7..."]:17: [string "/home/johan/data/src/huespace/extern/redhat-7..."]:15: [string "/home/johan/data/src/huespace/extern/redhat-7..."]:17: [string "/home/johan/data/src/huespace/extern/redhat-7..."]:25: [string "/home/johan/data/src/huespace/extern/redhat-7..."]:17: [string "/home/johan/data/src/huespace/extern/redhat-7..."]:25: [string "/home/johan/data/src/huespace/extern/redhat-7..."]:18: [string "/home/johan/data/src/huespace/extern/redhat-7..."]:25: Cannot allocate memory`

- The machine is not running out of memory, the Doxyrest process seems to use about ~1GB at this point.
- I have increased the amount of open files for my user account to 16K file handles, which should be enough? Could there be other system limits that I am hitting?
- I did try running it under gdb, but I did not get a SIGNAL/backtrace so it seems like some Doxyrest error handling code is picking up the error and exiting gracefully. 

I am willing to spend some time in gdb in order to track this down, but I was wondering if you have any ideas on where to start.

**Comment by vovkos** [comment]
Could you please provide a link to your project? Or maybe, just upload somewhere a ``.tar.xz`` of this XML database so that I can try and reproduce the issue on my machine? 

7000 files doesn't sound like it's too many, we should be able to process it. Maybe, something's leaking or there is something to fix in the algorithms/design. In any case, I would like to reproduce it locally before coming to any conclusions.

Thanks!

**Comment by johanseland** [comment]
Hello, and sorry for the long delay. Since this is a closed-source product I had to get permission to share the XML database before I could proceed. This obviously took it's time over Christmas.

In the end I did get permission, but I cannot link to the archive in an open forum. Could you please contact me by email (johan.seland @ bluware.com) so I can send you the link to the archive?

**Comment by vovkos** [comment]
Thanks for the XML database! I was able to reproduce the issue.

Indeed, the memory mapped regions were not properly freed on POSIX (Linux, macOS), which led to system resource exhaustion in the long run. A fix is pushed, please try again with the latest commits to ``master``. The fix is actually in ``axl``, but the bundle repo ``doxyrest_b`` is already auto-updated; just make sure to update git submodules.

Let me know how it works for you!

**Comment by johanseland** [comment]
I can confirm that the fix to `axl` indeed solves the problem, and that I am now fully able to use Doxyrest as I want in our documentation pipeline.

Thank you so much for your very quick turnaround time!
