### ISSUE TITLE
doxyrest-mac-1.1.0 is hard-linked to /usr/local/opt/lua/lib/liblua.5.2.dylib

### ISSUE THREAD

**Issue by esg-jayallan** [vovkos/doxyrest#6]
Downloading doxyrest-mac-1.1.0 from `https://github.com/vovkos/doxyrest/releases/tag/doxyrest-1.1.0` and executing `doxyrest` on macOS High Sierra 10.13.4 results in the following error:
```
dyld: Library not loaded: /usr/local/opt/lua/lib/liblua.5.2.dylib
  Referenced from: /Users/user/Downloads/doxyrest-mac-1.1.0/bin/./doxyrest
  Reason: image not found
```

The latest version of Lua is installed on the system via `homebrew`:
```
$ lua -v
Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio
```

`usr/local/opt/lub/lib/` contains a `liblua.5.3.4.dylib` which should be compatible with Lua 5.2.

As a workaround, I had to copy this dynamic library to the expected location:
`cp /usr/local/opt/lua/lib/liblua.5.3.4.dylib /usr/local/opt/lua/lib/liblua.5.2.dylib`

**Comment by vovkos** [comment]
Actually, lua-5.2.x is NOT binary compatible with lua-5.3.x; I'm pretty sure they have had some breaking API changes -- hence, the SONAME also had changed. It might still work with doxyres because doxyrest probably doesn't invoke the functions that changed. But renaming liblua.5.3 and use it instead of 5.2 is just NOT the right thing to do.

I use homebrew to install lua on Travis CI (where the release binary is built) and apparently at the time of the build the version of lua on homebrew was 5.2. As of now, it seems like there's no homebrew formula for installing lua-5.2, so you can't just use homebrew to install lua-5.2 side-by-side with lua-5.3.

To really solve this problem without any workarounds, I better modify the CI scripts and build doxyrest using static linking to liblua; this way there will be no runtime dependencies on the lua dylib.

**Comment by esg-jayallan** [comment]
You are right. I don't have any experience with Lua and just assumed they would not introduce any breaking changes with a minor version change. Doxyrest will quit with multiple errors when actually trying to parse Doxygen's output using Lua 5.3.x.

As a workaround, I therefore manually copied an actual `liblua.5.2.dylib` to the expected location but having Doxyrest statically linked to `liblua` in an upcoming release would be appreciated.

Thanks!

**Comment by vovkos** [comment]
When built on Travis CI for Mac OSX, Doxyrest is statically linked to liblua52.a from lua-5.3.4 -- so there's no dependency on external Lua .dylib anymore.

**Comment by bilke** [comment]
I tried the actual version 2.1.3 on macOS and git a similar error:

```
dyld[88308]: Library not loaded: /usr/local/opt/lua/lib/liblua.dylib
  Referenced from: /Users/bilke/Downloads/doxyrest-2.1.3-mac/bin/doxyrest
  Reason: tried: '/usr/local/opt/lua/lib/liblua.dylib' (no such file), '/usr/local/lib/liblua.dylib' (no such file), '/usr/lib/liblua.dylib' (no such file)
```

It would be awesome if you could release a binary without the dylib dependency! Thanks!

**Comment by bilke** [comment]
I just checked 2.1.2 and it worked!
